### ISSUE TITLE
Remote poweron (KEY_POWER) suddenly broken

### ISSUE THREAD

**Issue by twf75** [kdschlosser/samsungctl#95] opened 2019-02-01 14:18 UTC
Since one of the latest commits, the KEY_POWER has stopped working. In the earlier versions, KEY_POWER worked for turning on my Q7. Now it fails with:

 Max retries exceeded with url: /rcr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73c9d430>: Failed to establish a new connection: [Errno 113] No route to host',))

 Using wake_on_lan.py with the ip works fine, and it worked fine on earlier commits.

**Comment by twf75** [comment] 2019-02-01 18:34
No rush man! But yeah, that sounds logical to me (so much so that I thought that was the way it works right now...)

**Comment by kdschlosser** [comment] 2019-02-01 18:59
I know that is what people thought. that is the way it should work...

the library has been updated.

**Comment by kdschlosser** [comment] 2019-02-01 19:02
Samsung TV's do not have the ability to be powered on from a key code..  I know I know do not ask me why there is a KEY_POWERON. but samsung goes have that keycode... the keycodes are not just for their TV's it is for all of their devices..

on some TV's the KEY_POWEROFF will turn the TV off. while on others the KEY_POWER will turn it off. the KEY_POWERON did nothing.

so now the behavior is as such..

KEY_POWER = toggle
KEY_POWERON = power on
KEY_POWEROFF - power off.

the library will handle what needs to be done. so the user will not have to worry about it.

**Comment by twf75** [comment] 2019-02-01 19:10
Just updated. Same result:

requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.16', port=7676): Max retries exceeded with url: /rcr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73d43490>: Failed to establish a new connection: [Errno 113] No route to host',))

for KEY_POWERON and KEY_POWER

While the TV is on, the KEY_POWER and KEY_POWEROFF commands now causes the TV to cycle between power on and power off, until I send a break to the script. 

The happy news is that whatever is causing the TV to powercycle from an on state IS able to turn ON the TV ;)

**Comment by kdschlosser** [comment] 2019-02-01 19:36
> While the TV is on, the KEY_POWER and KEY_POWEROFF commands now causes the TV to cycle between power on and power off, until I send a break to the script.

explain this better..
is it looping between power on and off over and over again??

**Comment by kdschlosser** [comment] 2019-02-01 19:37
i fixed this issue.

requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.16', port=7676): Max retries exceeded with url: /rcr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73d43490>: Failed to establish a new connection: [Errno 113] No route to host',))

the library has been updated.

**Comment by twf75** [comment] 2019-02-01 19:50
Same behaviour for POWER/POWEROFF (the cycle):

pi@raspberrypi:~/samsungctl $ samsungctl KEY_POWEROFF --config-file /home/pi/woonkamer.conf
^CTraceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 353, in main
    key(remote)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/key_mappings.py", line 12, in __call__
    remote.control(self.key)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_websocket.py", line 306, in control
    self.power = False
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_websocket.py", line 281, in power
    event.wait(2.0)
  File "/usr/lib/python2.7/threading.py", line 614, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt

**Comment by twf75** [comment] 2019-02-01 19:50
Also same behavior for POWER_ON / POWER from an OFF state:

pi@raspberrypi:~/samsungctl $ samsungctl KEY_POWEROFF --config-file /home/pi/woonkamer.conf
^CTraceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 353, in main
    key(remote)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/key_mappings.py", line 12, in __call__
    remote.control(self.key)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_websocket.py", line 306, in control
    self.power = False
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_websocket.py", line 281, in power
    event.wait(2.0)
  File "/usr/lib/python2.7/threading.py", line 614, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt

**Comment by kdschlosser** [comment] 2019-02-01 20:04
OK here is what I am going to do. right now I have the library set up so it keeps on retrying to send the commands..

I am willing to bet you any amount of money.. this is the shit ass thing samsung did.
because I do not know which key works on what TV's either the KEY_POWER or the KEY_POWEROFF i am sending both of them...

Samsung actually does have the KEY_POWER set up as a toggle. this is the hoot.. because I am doing a loop and retrying to the keys. it is happening to fast. and the KEY_POWER is toggling the TV off. and then before the websocket gets a chance to close the KEY_POWER gets sent again.. and the TV turns back on.. LOL

So.. I am going to fire the KEY_POWER first.. then the KEY_POWEROFF and each one will get fired only a single time. no looping..

I am going to  have to keep the loop with the WOL packets. this is because a WOL packet is a broadcast an the TV may not get the packet.. broadcasting can have that issue. and it should be expected that a packet may not get where it is supposed to go. and the programming code should account for this.

as far as that last error.... I never thought about the UPNP and the TV being off. LOL.. i will have to fix that as well.

the old version of samsungctl will simply error out if the TV is off. I have expanded it's functionality to handle the TV being off so I need to make the library fully capable of dealing with the TV when it is off. and this is did not do with the upnp side of things...

it is going to take me a whiile to hammer that out, so give me a half a day or so.

**Comment by twf75** [comment] 2019-02-01 20:09
Again, no rush! Just very happy that you are doing this, so I'm the last one that'll make demands on your time. 

And while you are in there (and I haven't checked myself) : Does the --start-app check power state?

**Comment by kdschlosser** [comment] 2019-02-01 20:19
every command does. if the TV power is on but the websocket connection is not made. it will make it. of the power is off. it will print a log statement saying the TV is off and continue along it's merry way.

**Comment by kdschlosser** [comment] 2019-02-02 07:07
if you want to test out the new power handling.. clone the develop branch.

**Comment by twf75** [comment] 2019-02-02 09:58
Cloned the develop branch with:
git clone  https://github.com/kdschlosser/samsungctl.git develop
cd develop/
sudo python setup.py install

Verified /usr/local/bin/samsungctl is the current date/time

KEY_POWER and KEY_POWEROFF still cycle from on to off to on etc

pi@raspberrypi:/usr/local/bin $ samsungctl KEY_POWEROFF --config-file /home/pi/woonkamer.conf
^CTraceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 353, in main
    key(remote)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/key_mappings.py", line 12, in __call__
    remote.control(self.key)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_websocket.py", line 306, in control
    self.power = False
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_websocket.py", line 279, in power
    self.send("ms.remote.control", **power)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_websocket.py", line 233, in send
    self.send_event.wait(0.3)
  File "/usr/lib/python2.7/threading.py", line 614, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt

**Comment by twf75** [comment] 2019-02-02 09:59
New behaviour for KEY_POWERON:

pi@raspberrypi:/usr/local/bin $ samsungctl KEY_POWERON --config-file /home/pi/woonkamer.conf
Traceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 338, in main
    with Remote(config) as remote:
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 82, in __call__
    return RemoteWrapper(conf)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 69, in __init__
    self
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/__init__.py", line 20, in __init__
    UPNPObject.__init__(self, ip, locations)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/UPNP_Device/upnp_class.py", line 35, in __init__
    response = requests.get(location)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.21.0-py2.7.egg/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.21.0-py2.7.egg/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.21.0-py2.7.egg/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.21.0-py2.7.egg/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.21.0-py2.7.egg/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.1.16', port=9119): Max retries exceeded with url: /screen_sharing (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x73cab450>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by twf75** [comment] 2019-02-02 10:00
Behaviour for KEY_POWER (also from off state) seems unchanged to the main branch.

**Comment by kdschlosser** [comment] 2019-02-02 10:31
also your first error is because of you interrupting the script. it is going to take a bit for the TV to power down. so the script waits until it is off before it will exit. it will look like it is doing nothing for up to 10 seconds.

**Comment by twf75** [comment] 2019-02-02 10:36
> also your first error is because of you interrupting the script. it is going to take a bit for the TV to power down. so the script waits until it is off before it will exit. it will look like it is doing nothing for up to 10 seconds.

The interrupt is because at that point the TV went off, then on again. As the plan was 'turn off', I've taken 'turning on again' as 'not working' ;-)

**Comment by twf75** [comment] 2019-02-02 10:38
pi@raspberrypi:~/develop/develop $ samsungctl KEY_POWERON --config-file /home/pi/woonkamer.conf
Traceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 338, in main
    with Remote(config) as remote:
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 81, in __call__
    return RemoteWrapper(conf)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 68, in __init__
    config.upnp_locations
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/__init__.py", line 19, in __init__
    self.name = self.__name__
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/UPNP_Device/upnp_class.py", line 130, in __getattr__
    if item in self._devices:
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/UPNP_Device/upnp_class.py", line 130, in __getattr__

Last 3 lines repeated a couple of hunderd times

RuntimeError: maximum recursion depth exceeded while calling a Python object

TV was off, command was KEY_POWERON. KEY_POWER behaves the same.

**Comment by kdschlosser** [comment] 2019-02-02 10:38
ahh ok.. yes that would be not working. But the traceback does not help because of the interruption

I just updated the develop branch again.

**Comment by twf75** [comment] 2019-02-02 10:39
Same result for KEY_POWEROFF from an ON state.

**Comment by twf75** [comment] 2019-02-02 10:39
Pulling the new one now :)

**Comment by kdschlosser** [comment] 2019-02-02 10:40
pull this one..
i just fixed that last traceback.

**Comment by twf75** [comment] 2019-02-02 10:43
Same response as above. But now the script hangs up at the end. Can't be interrupted even...

  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/UPNP_Device/upnp_class.py", line 130, in __getattr__
    if item in self._devices:
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/UPNP_Device/upnp_class.py", line 130, in __getattr__
    if item in self._devices:
RuntimeError: maximum recursion depth exceeded while calling a Python object
^C

KEY_POWEROFF in this case, from an ON state.

**Comment by kdschlosser** [comment] 2019-02-02 10:45
try it now.

**Comment by twf75** [comment] 2019-02-02 10:46
Sorry :(

  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/UPNP_Device/upnp_class.py", line 130, in __getattr__
    if item in self._devices:
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/UPNP_Device/upnp_class.py", line 130, in __getattr__
    if item in self._devices:
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/UPNP_Device/upnp_class.py", line 130, in __getattr__
    if item in self._devices:
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/UPNP_Device/upnp_class.py", line 130, in __getattr__
    if item in self._devices:
RuntimeError: maximum recursion depth exceeded while calling a Python object
^C
^C

**Comment by kdschlosser** [comment] 2019-02-02 10:48
i need to see the beginning of the error

**Comment by twf75** [comment] 2019-02-02 10:48
My bad:

pi@raspberrypi:~/develop/develop $ samsungctl KEY_POWEROFF --config-file /home/pi/woonkamer.conf
Traceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 338, in main
    with Remote(config) as remote:
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 83, in __call__
    return RemoteWrapper(conf)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 70, in __init__
    config.upnp_locations
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/__init__.py", line 23, in __init__
    self.connect_upnp()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/UPNP_Device/upnp_class.py", line 130, in __getattr__
    if item in self._devices:
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/UPNP_Device/upnp_class.py", line 130, in __getattr__
    if item in self._devices:

**Comment by kdschlosser** [comment] 2019-02-02 10:56
I updated it again.

**Comment by twf75** [comment] 2019-02-02 11:00
pi@raspberrypi:~/develop/develop $ samsungctl KEY_POWEROFF --config-file /home/pi/woonkamer.conf
Traceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 338, in main
    with Remote(config) as remote:
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 73, in __call__
    return RemoteWrapper(conf)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 60, in __init__
    config.upnp_locations
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/__init__.py", line 29, in __init__
    self.connect_upnp()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/upnp/UPNP_Device/upnp_class.py", line 134, in __getattr__
    raise AttributeError(item)
AttributeError: connect_upnp
  ^C

Script hangs at this point, had to kill -9 it.

**Comment by kdschlosser** [comment] 2019-02-02 11:02
OK I think i have it solved this time.

**Comment by twf75** [comment] 2019-02-02 11:05
In the sense that the TV actually turned off this time: YES!

However...

pi@raspberrypi:~/develop/develop $ samsungctl KEY_POWEROFF --config-file /home/pi/woonkamer.conf
Traceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 408, in main
    remote.source = args.source
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 71, in __exit__
    self.close()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/websocket_base.py", line 140, in close
    raise NotImplementedError
NotImplementedError

(Script again hangs, ^C does nothing)

**Comment by twf75** [comment] 2019-02-02 11:06
POWER_ON works too, other than hanging up the script (which may be at my end)

**Comment by twf75** [comment] 2019-02-02 11:07
Gave it a couple minutes after hanging:

pi@raspberrypi:~/develop/develop $ samsungctl KEY_POWERON --config-file /home/pi/woonkamer.conf
^CTraceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 408, in main
    remote.source = args.source
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote.py", line 71, in __exit__
    self.close()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/websocket_base.py", line 140, in close
    raise NotImplementedError
NotImplementedError

The TV does turn on though!

**Comment by kdschlosser** [comment] 2019-02-02 11:08
close error should now be fixed.

**Comment by twf75** [comment] 2019-02-02 11:13
ON does work (in that the TV turns on) but hangs:

pi@raspberrypi:~/develop/develop $ samsungctl KEY_POWERON --config-file /home/pi/woonkamer.conf
^CTraceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.8.0b0', 'console_scripts', 'samsungctl')()
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/__main__.py", line 353, in main
    key(remote)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/key_mappings.py", line 12, in __call__
    remote.control(self.key)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_websocket.py", line 279, in control
    self.power = True
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/utils.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/remote_websocket.py", line 225, in power
    event.wait(2.0)
  File "/usr/lib/python2.7/threading.py", line 614, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt

**Comment by twf75** [comment] 2019-02-02 11:13
Hold, testing the new one.

**Comment by kdschlosser** [comment] 2019-02-02 11:19
try it again,

**Comment by kdschlosser** [comment] 2019-02-02 11:31
try it again.

**Comment by kdschlosser** [comment] 2019-02-02 11:32
also when the TV is on use your browser and go to this URL..

 http://192.168.1.16:9119/screen_sharing

see if it is valid

**Comment by twf75** [comment] 2019-02-02 11:37
From an OFF state: KEY_POWER works, TV turns on (and is quite fast)
From an ON state: KEY_POWER works , TV turns off (less fast, but acceptable)
From an OFF state: KEY_POWERON works, TV turns on (feels slower than KEY_POWER)
From an ON state: KEY_POWEROFF works, TV turns off (about the same as KEY_POWER)

All commands exit gracefully. So this feels fixed :)

http://192.168.1.16:9119/screen_sharing is a valid URL with the TV on. Times out while the TV is off.

**Comment by kdschlosser** [comment] 2019-02-02 11:38
try it now...

I am trying to shrink thee power on time.

**Comment by kdschlosser** [comment] 2019-02-02 11:41
KEY_POWER should operate at the same speed as KEY_POWERON and KEY_POWEROFF. it is running the same code as those keys do.

**Comment by twf75** [comment] 2019-02-02 11:42
KEY_POWERON : about 17 seconds
KEY_POWEOFF : About 13 seconds, TV turns off in the first 5. 
KEY_POWER with TV off : About 17 seconds, TV turns on after about 12 seconds. 
KEY_POWER with TV on: About 12 seconds, TV turns off after 3 seconds. \

Times are total execution times, counted manually :)

**Comment by twf75** [comment] 2019-02-02 11:43
> KEY_POWER should operate at the same speed as KEY_POWERON and KEY_POWEROFF. it is running the same code as those keys do.

Right, I'll skip KEY_POWER in next tests :)

**Comment by kdschlosser** [comment] 2019-02-02 11:46
there are no next tests..

There is a difference between the TV screen coming on or turning off and the actual services that are available on the TV. the first thing the TV is going to do is power the screen or turn the screen off. the last thing it will do is start and stop any services.

so that is why you see a time difference between the TV being perceived as on or off and when thee program says it is on or off.


I have the loop that checks the power state set to wait 1 second between loops. so it is as fast as I am going to be able to make it..

**Comment by kdschlosser** [comment] 2019-02-02 11:46
if you are going to be online for a few minutes. I want to hammer together a new interactive mode.. it should only take me a few minutes to code up.

**Comment by twf75** [comment] 2019-02-02 11:47
I'm here for the next 30 minutes or so, do your worst ;)

**Comment by twf75** [comment] 2019-02-02 11:48
Very happy with the outcome so far, and kudo's to you sir!

**Comment by kdschlosser** [comment] 2019-02-02 12:15
OK all done...

use --interactive at the command line.. along with the --config-file..

**Comment by twf75** [comment] 2019-02-02 12:15
Willdo. Give me a moment.

**Comment by kdschlosser** [comment] 2019-02-02 12:16
cool beans.. and I just finished in the nick of time.. 28 minutes to code it from scratch..

**Comment by twf75** [comment] 2019-02-02 12:37
Some spare comments:

- Still can't get over how fast KEY_POWER powers on the TV from interactive...
- Entering 'key_mute' instead of 'KEY_MUTE' silently fails.
- No command history, so arrow-up does nothing useful. Not terribly important though. 
- Rubbish input leads to an error:

Please enter command:argdfgs
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/samsungctl-0.8.0b0-py2.7.egg/samsungctl/interactive.py", line 97, in run
    value = int(value)
ValueError: invalid literal for int() with base 10: 'rgdfgs'

The program does continue though.

**Comment by kdschlosser** [comment] 2019-02-02 12:46
it is supposed to continue.. the error is what it is supposed to do,

I will work on adding the up arrow and down arrows for scrolling through previous commands. as well as escape to clear an already entered command.

It's a good thing I have already messed around with cursor movements cross platform.. :smile:

I also removed the need to enter KEY_ in the command.

**Comment by twf75** [comment] 2019-02-02 13:04
Noice! Let me know when you need more testing. Happy to help.

**Comment by kdschlosser** [comment] 2019-02-03 00:09
I  closing this everything should be working fine.

**Comment by twf75** [comment] 2019-02-03 09:09
Yup, everything works, I'm a happy camper. Thanks! I'll stay on the develop branch for now.

**Comment by kdschlosser** [comment] 2019-02-03 10:38
ok cool.

**Closed by kdschlosser** 2019-02-03 10:38 UTC
